### ISSUE TITLE
TO DO LIST

### ISSUE THREAD

**Issue by Nemixalone** [Nemixalone/GUI-tool-for-InstaPy-script#1]
List for improvement and more options

- [ ] Save all button - To save all settings,e.g. tags,checked options, all values.

- [x] Notification for dangerous use of tool !!

- [ ] Change Split function - Should split by other char than **coma** _( , )_  e.g. _~_

- [x] Add Run last script

> All contributors will be credited

**Comment by gethubuser24** [comment]
I noticed you had the .exe located in the following areas
GUI-tool-for-InstaPy-script-master\InstaPy\bin\Debug
GUI-tool-for-InstaPy-script-master\InstaPy\obj\Debug

Does it matter which get used?
