### ISSUE TITLE
Wrong Login Data!

### ISSUE THREAD

**Issue by peterz001** [Nemixalone/GUI-tool-for-InstaPy-script#10]
Hi,  I was able to run the  exe, i entered my credentials and a tag "cats". Then i pressed "Run".
This opened the chrome browser, went to instagram, automatically inputted my username and password and then logged in.After this, the browser closes and in the command window i get this message 

> C:\Users\InstaPy-master>set PYTHONIOENCODING=UTF-8
> C:\Users\InstaPy-master>py quickstart.py
> Wrong login data!
> Session ended
> -------------

I'm a newbie in this area, any help would be appreciated! :)

**Comment by Nemixalone** [comment]
Hm since it`s InstaPy error i need to ask you to put that issue on official InstaPy page since i don`t know how InstaPy actually works. Thanks
