### ISSUE TITLE
There is no instapy-gui.exe file in the download.

### ISSUE THREAD

**Issue by ujazzz** [Nemixalone/GUI-tool-for-InstaPy-script#11]
This is a bit confusing as I'm ver ynew to programming. I have installed Selenium, pyvirtual library and pip. 

You mentioned this -
| Extract it and put InstaPy-GUI.exe inside InstaPy folder

I'm not able to find this file.

**Comment by Nemixalone** [comment]
[Here](https://github.com/Nemixalone/GUI-tool-for-InstaPy-script/releases/tag/0.4) is latest version of .exe file.
