### ISSUE TITLE
Exe file missing

### ISSUE THREAD

**Issue by jeffreylm** [Nemixalone/GUI-tool-for-InstaPy-script#15]
Dear Team,

I downloaded the zip file. There is no exe file.
I don't get where the explanation says "No install just download the file and put the exe in the instpy directory.
What you need to always do is give the instructions to a nubie and see what happens, someone like an aunt or uncle. You will quickly see when the instructions is missing key data that may reside in your head that you fill in automatically without realizing. 

Where can I find the .exe file to download?

Jeffrey

**Comment by Nemixalone** [comment]
You can find it on [release page](https://github.com/Nemixalone/GUI-tool-for-InstaPy-script/releases) and there is [InstaPy-GUI.exe](https://github.com/Nemixalone/GUI-tool-for-InstaPy-script/releases/download/0.5/InstaPy-GUI.exe)(<- click to download) file. You have downloaded main part of InstaPy with that **.zip** file (GUI is optional not necessary for InstaPy to work just makes it easier)

**Comment by jeffreylm** [comment]
@Nemixalone Thank you
