### ISSUE TITLE
Can't use GUI

### ISSUE THREAD

**Issue by JustJaylen** [Nemixalone/GUI-tool-for-InstaPy-script#16]
<img width="678" alt="gui" src="https://user-images.githubusercontent.com/30621459/28820368-57b42cb4-76a9-11e7-9b33-0a86aff84151.png">
As you can see only part of the GUI pops up and not the whole thing and I can't make it smaller to actually see or try and use the run button so the application runs

**Comment by Nemixalone** [comment]
Yes I am aware of the problem I didn't considered the laptop screen sizes (made for 1080p for now), but will try asap to fix it and include a scrollbar. Stay tooned.

**Comment by Nemixalone** [comment]
@JustJaylen I fixed the problem you can download a [fresh app](https://github.com/Nemixalone/GUI-tool-for-InstaPy-script/releases/download/0.6/InstaPy-GUI.exe) from that link. 

Enjoy using it. :smile: :100:

**Comment by JustJaylen** [comment]
Thanks!
