### ISSUE TITLE
Tag field

### ISSUE THREAD

**Issue by jeffreylm** [Nemixalone/GUI-tool-for-InstaPy-script#17]
Hello,

One of the things that would really make this GUI more useable is if the Tag field could be multilined. It has to be able to accomadate the 30 tag in a clear fashion. There is so much realestate on my screen that isn't used.

That field could be put at the bottom expanded accross both halves of the application screen.

**Comment by Nemixalone** [comment]
Hi,

You can type as many tags as you want. I know it's not prettiest solution and I will keep that in my mind for future redesigns.

**Comment by jeffreylm** [comment]
Hello, I know you can type many tags, but my point is that the user friendly aspect of it, not the prettiness of it. It is difficult to work in that slither of a line with so many variable. And yes, you can go back and forth between a text editor, but then the question will be. How difficult is it to make the filed a multiline area?
