### ISSUE TITLE
Instapy like amount issue?

### ISSUE THREAD

**Issue by johnnydavis60** [Nemixalone/GUI-tool-for-InstaPy-script#18]
Lets say I choose to like 150 of the hashtag music. The cmd prompt will show that it will only like a much lower number like 20 or 30. Why is that, I chose 150, it should start to like 150, shouldn't it? Sometimes it will like the amount I chose but recently it hasn't been.

**Comment by Nemixalone** [comment]
Don't minimize **chrome window** since it won't load all pictures.
