### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by pedroricardo** [Nemixalone/GUI-tool-for-InstaPy-script#19]
![image](https://user-images.githubusercontent.com/25847896/29390061-580eef38-82c4-11e7-9402-a4cd3e52cffc.png)
Does this error repeat itself how can I solve it?

**Comment by pedroricardo** [comment]
Inside the root of the repository? 
https://github.com/timgrossmann/InstaPy
I already coloqui it and got msg

**Comment by Nemixalone** [comment]
Close that window and start app from inside folder. Maybe you are missing chromedriver.exe inside **assets* folder.

**Comment by pedroricardo** [comment]
Chormedrive.exe is already in the correct folder, just send the tutorial.

I executed the application as requested in the master folder and I still got an error: /

**Comment by Nemixalone** [comment]
You have notification next to the **RUN** button what is missing and what has been downloaded. There is no tutorial, there is **readme** which I HIGHLY recommend. Maybe you deleted some important files please download newest version of **GUI** and **Instapy**. After u extract instapy put **GUI** inside root folder and download chromedriver.exe and pu it inside **assets**. Thats all if that doesn't work then we have **bug** which i will try to solve **asap**

**Comment by willdaube** [comment]
When I get to step 3 I get an error while running windows.ps. I may be misunderstanding the instructions( I'm relatively new to this and a musician by trade). When running this code in cmd prompt on my windows 10 system I get an error saying it can't find setup.py and that several of the commands are not recognized. What am I doing wrong? Should I be running this script somewhere else?
