### ISSUE TITLE
Problem Using the Gui

### ISSUE THREAD

**Issue by marudonart** [Nemixalone/GUI-tool-for-InstaPy-script#2]
Hallo,
great project :-)
Unfortunately I'm not able to bring the Gui to do something.. when I press run nothing happens (no error message). I copied the InstaPy.exe in the main folder.

How do I know if or when the script works?
Are my Gui Inserts wrong? 
My Follower Range is very high (starting at 20.000), but the chosen tags should even have some hits .. the windows task manager shows no activities on the instaPy task.

Thanks for the Support :-)
Stefan

**Comment by Nemixalone** [comment]
Hello @marudonart and thank you,

First this is outdated version of GUI since there was updates for InstaPy script, try downloading new one from release page.
Second go to InstaPy folder and press **shift + right click** and **Open command window here** and type **Start.bat** and run it. See if there is any errors in script. 
And please report back if that worked. 
Thanks :+1:

**Comment by marudonart** [comment]
Thanks for your quick reply :-)
I will check it this evening and report you then.

By the way, I wondered if there is a possibility to find out how many
likes, comments and following/unfollowing actions the tools does and at
what account or tags at what time? What are the delays between actions? A
reporting or logging would be nice .. to get a better control and not to
overact the use of the tool.

Looking forward to work with your tool, thanks for providing :-)
Stefan

(from Munich/Germany)

**Comment by Nemixalone** [comment]
This tool is mainly for generating script so dont have to write down the code. For more information how script works or any trouble with the script it self please post on/and read official [InstaPy](www.github.com/timgrosmann/InstaPy) documentation. The logging idea would be nice post it in Issue tab on their page. And try not to exceede 1000post/day IG can ban your account.  

Nemanja Komadina

**Comment by marudonart** [comment]
Hello Nemanja,
I'm a little bit confused: I download once more
the GUI-tool-for-InstaPy-script.zip from your github page and unzipped it.
Now it has a new structure .. there is no start.bat anymore. But there is a
new zip file called master.zip?

When I started the Gui once more I get the message 'instaPy folder is
missing'

What did I wrong?

Regards,
Stefan

**Comment by marudonart** [comment]
I also downloaded the newest Chrom Driver 2.29 , unzipped it and run it (see attachment). Nevertheless the Gui messages 'Chrom Driver is missing'

![image](https://cloud.githubusercontent.com/assets/27830829/25293268/510662f2-26da-11e7-9c6c-b98d1a84277e.png)

**Comment by Nemixalone** [comment]
Go to release tab and download .exe only InstaPy-GUI.exe put it in main folder of InstaPy, chromedriver put into assets folder.

**Comment by marudonart** [comment]
The problem with the crom driver is fixed and the Gui works fine, but I still can't run Python behind it. The command "py" ist not found when executing ..do I have to install a Python Runtime or set a parm to find Python runtime ?

![image](https://cloud.githubusercontent.com/assets/27830829/25299510/3706bb92-2700-11e7-9187-5d1a24034d3f.png)

**Comment by marudonart** [comment]
Now I downloaded and installed Python 3 and I set the path parm. 
http://www.chip.de/downloads/Python-3_22363252.html

Now I get the error message "Can't find a default python"

![image](https://cloud.githubusercontent.com/assets/27830829/25299796/30b10240-2703-11e7-9a2e-b079c1e7e964.png)

**Comment by Nemixalone** [comment]
You don't have [Python](https://www.python.org/downloads/) installed ?

**Comment by marudonart** [comment]
No .. why didn't you write in the instruction .. I'm not a python developer

**Comment by Nemixalone** [comment]
Well I already told you the official page is [InstaPy](https://github.com/timgrossmann/InstaPy) this here is only GUI for GENERATING the script.

**Comment by marudonart** [comment]
At the official page is no info that there have to be installed Python, .. and there the instructions are not written for a windows system

**Comment by marudonart** [comment]
No I should be close to running Python, but what mdoes it mean  "Can't find a default python"  .. wrong path or maybe have to reboot my computer after installation?

**Comment by Nemixalone** [comment]
Try to type **python quickstart.py**

**Comment by Nemixalone** [comment]
1. Open Control Panel » System » Advanced » Environment Variables.
Click New and type like on the picture but VALUE must be where you have installed Python
![zxc](https://cloud.githubusercontent.com/assets/7568344/25299929/51bb8a94-2705-11e7-9803-06261b8c93af.png)

**Comment by marudonart** [comment]
I added a variable py and inserted the path where I installed Python ..
but still the same problem

![image](https://cloud.githubusercontent.com/assets/27830829/25300013/c486d4b0-2706-11e7-8b20-3721528ee893.png)

**Comment by Nemixalone** [comment]
Can you please download Python from official page down below and install it somewhere else than in APPDATA e.g. like my install path and set paths to that.

https://www.python.org/downloads/release/python-361/

**Comment by marudonart** [comment]
I uninstalled Python and installed the official version
https://www.python.org/downloads/release/python-361/

Now the new path is *C:\Program Files (x86)\Python36-32*

But I don't have a folder  *\py\Scripts*   .. so I can't set this path
What should be there inside? More secret things to know?


Do you have Skype? Meine name is "heisse_herdplate"  Would be easier to
solve the problem .. :-)

**Comment by marudonart** [comment]
It looks like Python is found now, but something is missing ..


-------------------------------------------
E:\InstaPy_neu\InstaPy-master>*start.bat*

E:\InstaPy_neu\InstaPy-master>set PYTHONIOENCODING=UTF-8

E:\InstaPy_neu\InstaPy-master>py quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "E:\InstaPy_neu\InstaPy-master\instapy\__init__.py", line 1, in
<module>
    from .instapy import InstaPy
  File "E:\InstaPy_neu\InstaPy-master\instapy\instapy.py", line 5, in
<module>
    from pyvirtualdisplay import Display
ModuleNotFoundError: No module named 'pyvirtualdisplay'

**Comment by Nemixalone** [comment]
That is a good error now. Go to **C:\Program Files (x86)\Python36-32\Scripts** (no py\scripts)  press **Shift + Right click** and **Open command window here** and type **pip install selenium**

**Comment by marudonart** [comment]
the command pip is unkown

[image: Inline images 1]

**Comment by Nemixalone** [comment]
Is there a pip.exe or pip35.exe in Scripts folder? If there is pip35.exe just type commands with pip35 install....

**Comment by marudonart** [comment]
the script folder is complete empty ..

**Comment by marudonart** [comment]
.. maybe I installed to less when installing Python?

**Comment by Nemixalone** [comment]
Was there an option to install pip? Maybe try in this folder **/Lib/site-packages**

**Comment by marudonart** [comment]
I just reinstall at the moment .. add the pip

**Comment by marudonart** [comment]
.. but the reinstall process is buggy

[image: Inline images 1]

**Comment by Nemixalone** [comment]
Is there a pip now inside Scripts ? if yes try those commands from above for selenium and pyvirtualdisplay

**Comment by marudonart** [comment]
I cant reinstall as the uninstall process was buggy .. I have to repair my
registry manually ... :-(

**Comment by marudonart** [comment]
It is not possible to install the pip  .. the installation always ends with
an error see hardcopy
Is there a way to install pip manually ?


[image: Inline images 1]

**Comment by Nemixalone** [comment]
There is a [way](http://stackoverflow.com/questions/4750806/how-do-i-install-pip-on-windows). Try this.

**Comment by marudonart** [comment]
The script for manuel installation does not because permission problems
(also when I try under the admin role)

May you zip the script folder with all files and provide it via github ?

**Comment by Nemixalone** [comment]
[Here](http://www.mediafire.com/file/9bre58073lbba9e/Scripts.zip)

**Comment by marudonart** [comment]
Thanks, one step further .. I successfully installed Selenium

[image: Inline images 1]


but still the old error

[image: Inline images 2]

**Comment by Nemixalone** [comment]
you need to install **pyvirtualdisplay** also

**Comment by marudonart** [comment]
[image: Inline images 1]

**Comment by Nemixalone** [comment]
Cant see image

**Comment by marudonart** [comment]
C:\Program Files (x86)\Python36-32>pip install pyvirtualdisplay
Fatal error in launcher: Unable to create process using '"'

**Comment by Nemixalone** [comment]
python -m pip install pyvirtualdisplay

**Comment by marudonart** [comment]
one step further :-)     something more missing

    from clarifai.client import ClarifaiApi
ModuleNotFoundError: No module named 'clarifai'

**Comment by marudonart** [comment]
but I should have the python modul

[image: Inline images 1]

**Comment by Nemixalone** [comment]
Wait now there is no line ** from clarifai.client import ClarifaiApi ** in quickstart.py. Btw can't see images posted from mail.

**Comment by marudonart** [comment]
If I understand you right you deleted the import statement for ClarifaiApi?
But where? It never been in  quickstart.py .. you mean in instapy.py??  I
find no update in github ..

**Comment by Nemixalone** [comment]
I didn't deleted anything, import should not be in quickstart.py. Can you post full error here cause i don't know where the error comes from ?

**Comment by Nemixalone** [comment]
Wait are you using Clarifai for image check ?

**Comment by marudonart** [comment]
I delete "from clarifai.client import ClarifaiApi"  in instapy.py    ..
 now it looks like the python script is running :-)

Thanks for your patience :-)

**Comment by Nemixalone** [comment]
No problem :)
