### ISSUE TITLE
Follow someone else's followers

### ISSUE THREAD

**Issue by sjaakbanaan** [Nemixalone/GUI-tool-for-InstaPy-script#20]
Hi! Would be great if you could integrate the new 'Follow someone else's followers' functionality in to the GUI. Are you planning on doing this by any chance?

https://www.bountysource.com/issues/48361677-follow-someone-else-s-followers

**Comment by Nemixalone** [comment]
**Yes** I will try to do it **asap** but now I have a lot of stuff going on. My **guess** ETA of finishing is not before october. Sorry for inconvinience, but please understand me I am student and I have finals right now. 😞😞

**Comment by sjaakbanaan** [comment]
Hi @Nemixalone, thnx for answering. One of our clients is offering a 150 euro bounty (via bountysource.com) if you could build in this option in the GUI before the 22nd of September. Would you be interested in this or do you really need all the time for your finals?

**Comment by Nemixalone** [comment]
Can you provide full link to the bounty? Since it says that site is **not** **safe** !!

**Comment by sjaakbanaan** [comment]
I noticed the same thing.. Checked his [twitter](https://twitter.com/Bountysource) and it's just a temp. SSL issue. I've seen the creator of InstaPy using this platform to hand out bounties, that's how i stumbled upon it.

**Comment by Nemixalone** [comment]
22nd September ? To implement only **Follow someone else's followers** or all 5 functions ? I can do 3 out of 5.

**Comment by sjaakbanaan** [comment]
I will get back to you on this within a few hours!

**Comment by sjaakbanaan** [comment]
Those 3 options would be enough for now, so yes! Should I create the bounty now?

**Comment by Nemixalone** [comment]
Well how is that bounty collected?

**Comment by sjaakbanaan** [comment]
Via PayPal, in US dollars (so right now that's 179 US dollar). For more information on this platform check out: https://github.com/bountysource/core/wiki/Frequently-Asked-Questions

**Comment by Nemixalone** [comment]
Sure give me the link or however that work, I will start as soon as tomorrow morning, it might take 2-3 days to finish, when I post new release of .exe I can notify you by email and then we can proceed to collecting bounty.

**Comment by sjaakbanaan** [comment]
Sounds great man! I'll take care of the bounty today, thanks  :)

**Comment by sjaakbanaan** [comment]
Here it is: https://www.bountysource.com/issues/48361677-follow-someone-else-s-followers

**Comment by timgrossmann** [comment]
@sjaakbanaan @Nemixalone Holy s*** this is some insane bounty 😮

**Comment by Nemixalone** [comment]
hehe apparently some big clients are using our apps @timgrossmann :wink:

**Comment by sjaakbanaan** [comment]
Haha that's right guys, keep up the good work!

**Comment by timgrossmann** [comment]
@sjaakbanaan Make sure to keep the bounties realistic and take into consideration the work that users like @ahmadudin @BernardoGO put into getting this feature implemented into InstaPy itself, please 😉 

Congrats on your first bounty, @Nemixalone 👍

**Comment by Nemixalone** [comment]
Thanks :+1:

**Comment by sjaakbanaan** [comment]
@timgrossmann good point, I will in the future. These bounties are pretty new to us. Go buy the other guys some beers @Nemixalone ;)

**Comment by ahmadudin** [comment]
@timgrossmann thanks for tagging, now im feeling a bit jealous. Btw congrats @Nemixalone

**Comment by gnidorah** [comment]
@timgrossmann @sjaakbanaan Sorry, but why this bounty is insane and unrealistic? If someone can supply money instead of tips, that's very very good.

> take into consideration the work that users like @ahmadudin @BernardoGO put into getting this feature implemented into InstaPy itself, please

Sounds like resentment. No one forces them work for free and no one prevents them to hunt for bounties with good money. In addition there are BountySource's Salt, Patreon or similar projects to guide money into "right hands".

**Comment by Nemixalone** [comment]
Thanks :smile:  @ahmadudin 
@timgrossmann Does these two must combine or **session.set_user_interact** can stand for it self?

session.set_user_interact(amount=5, random=True, percentage=50, media='Photo')
session.follow_user_followers(['friend1', 'friend2', 'friend3'], amount=10, random=False, interact=True)

**Comment by timgrossmann** [comment]
@Nemixalone If you use the `interact=True`, it'll then take the tings defined in the `set_user_interact` 😉

**Comment by Nemixalone** [comment]
Ou and that is only in **follow_user_followers** ?

**Comment by Nemixalone** [comment]
@sjaakbanaan I have uploaded 0.7 version. 
You can find it on this [link](https://github.com/Nemixalone/GUI-tool-for-InstaPy-script/releases/tag/0.7). 
Any questions or bugs you can contact me. 
If everything is okay let me know. 

Cheers :beers:

**Comment by timgrossmann** [comment]
@Nemixalone If `interact=False` then you simply follow the users followers without interacting with them.

**Comment by sjaakbanaan** [comment]
Wow, that was quick @Nemixalone! I don't have time to check it out today but hopefully tomorrow. Hope you don't mind.

**Comment by Nemixalone** [comment]
Well i didnt start yesterday I started day before so 😂 No its okey whenever you can ✌🏻

**Comment by timgrossmann** [comment]
@sjaakbanaan Make him update the picture in the README 😜

**Comment by Nemixalone** [comment]
ehhehe its done :sweat_smile:  @timgrossmann

**Comment by sjaakbanaan** [comment]
Sorry @Nemixalone , still haven't had time but I will check it out tonight for sure!

**Comment by sjaakbanaan** [comment]
I checked it out and it works! Great stuff! Just two more questions (not sure if they are for you or for @timgrossmann though):
- whats the minimum sleep delay for the follow other users followers? T  tried something like 120 seconds but it gave me an error, 600 sec. worked fine. But in the examples of InstaPy he uses only 60 sec.  for delay. Am I doing something wrong?

**Comment by Nemixalone** [comment]
What is the error for first question, what does it says? And for the second one I cant tell anything since its Instapy question and I am not familiar with background work of it. It would be the best to wait for @timgrossmann 😊

**Comment by sjaakbanaan** [comment]
`session.follow_users_followers(['instaaccounthere' ], amount = 10, random=True, delay=60)`
`Typerror: follow_users_followers() got an unexpected keyword argument 'delay'`

**Comment by timgrossmann** [comment]
@ahmadudin @BernardoGO

**Comment by sjaakbanaan** [comment]
So this is not a GUI issue @timgrossmann ? In that case I can close this issue and @Nemixalone can collect his bounty...

**Comment by Nemixalone** [comment]
I think so but we can wait for confirmation

**Comment by Nemixalone** [comment]
@sjaakbanaan It was GUI bug you can download a new version from [here](https://github.com/Nemixalone/GUI-tool-for-InstaPy-script/releases/tag/0.7.1).  Sorry for bug. :disappointed: :cry:

**Comment by sjaakbanaan** [comment]
@Nemixalone Great news! I'm gonna test it tomorrow!

**Comment by sjaakbanaan** [comment]
@Nemixalone Works great man! Thanks all for the hard work. I'm going to close this issue now. Let me know if you need any help collecting the bounty (it's a first time for me as well).
