### ISSUE TITLE
All instapy files are there. but notworking

### ISSUE THREAD

**Issue by preenupaul** [Nemixalone/GUI-tool-for-InstaPy-script#21]
when clicking RUN the black box opens and automatically closes after 2 second.
why is this happening again and again. i installed all the software and everything is fine in my system

**Comment by jaguar754** [comment]
I have same issue. After click RUN app closes in 2 seconds.

**Comment by preenupaul** [comment]
Can someone make a Full video tutorial how to install all of these. I don't know coding and languages and all, i searched in youtube for video tutorials but no relevant videos.. I am a littile confused with the installation of selerium because its very confusing.

**Comment by mehdichekori** [comment]
Open the start.bat file
add " pause "  without the Quotation marks
this will let you see whats the error

**Comment by Nemixalone** [comment]
It's probably **InstaPy** error and not GUI problem.

**Comment by guldemkucuk** [comment]
after running the gui app pause comment in start.bat is deleted, so i still dont see the error

**Comment by Nemixalone** [comment]
It is **InstaPy** error somewhere. Go to folder find **quickstart.py**, **right click + shift** inside folder and click **open command window here** and type **start.bat** press enter and error should be seen.

**Comment by guldemkucuk** [comment]
Thanks, it worked now i can see the errors. 
I have fixed the problem via deleting clarifai import from insta.py and emoji import from comment_util.py 

I havent opened an issue. Later on i will check how I can add emoji module. Do i really need clarifai module, no idea why it is used.

**Comment by Nemixalone** [comment]
Clarifai is module for checking if image is SFW, more about that you can read on InstaPy page. I think you don't need that because a  lot of users are deleting that line. But emoji you can download via pip if you didnt already. **pip install emoji**

**Comment by guldemkucuk** [comment]
thanks Nemixalon:)  i will give it a try...
