### ISSUE TITLE
'python' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by preenupaul** [Nemixalone/GUI-tool-for-InstaPy-script#22]
C:\Python\Scripts>python -m pip install pyvirtualdisplay
'python' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Nemixalone** [comment]
Find where you installed **python**. You can do that by opening **CMD** and type **python** when loads type **import sys** and **sys.executable** and it will show you where you installed **Python**. Next go to **Scripts** folder and press **SHIFT + RIGHT CLICK** and **open new command window here** type **pip install pyvirtualdisplay**
