### ISSUE TITLE
Cmd closes instantly

### ISSUE THREAD

**Issue by pedronader** [Nemixalone/GUI-tool-for-InstaPy-script#23]
I´ve made everything right.
When I click on RUN the cmd opens and after some miliseconds it closes intantly.

What is the problem?

**Comment by Nemixalone** [comment]
Read issue #4 or #8

**Comment by pedronader** [comment]
I went to InstaPy folder press SHIFT then right click
Clicked on Open command window
Typed py quickstart.py

There is my error

C:\Users\Pedro Maurício\Desktop\InstaPy-master>py quickstart.py
Traceback (most recent call last):
File "quickstart.py", line 1, in 
from instapy import InstaPy
File "C:\Users\Pedro Maurício\Desktop\InstaPy-master\instapy_init_.py", lin
e 1, in 
from .instapy import InstaPy
File "C:\Users\Pedro Maurício\Desktop\InstaPy-master\instapy\instapy.py", line
8, in 
from pyvirtualdisplay import Display
ModuleNotFoundError: No module named 'pyvirtualdisplay'

What is wrong?

**Comment by Nemixalone** [comment]
pip install pyvirtualdisplay

**Comment by pedronader** [comment]
Tried this. Look what happened

__
C:\Users\Pedro Maurício\Desktop\InstaPy-master>pip install pyvirtualdisplay
Collecting pyvirtualdisplay
  Using cached PyVirtualDisplay-0.2.1.tar.gz
Requirement already satisfied: EasyProcess in c:\users\pedro maurício\appdata\lo
cal\programs\python\python36-32\lib\site-packages (from pyvirtualdisplay)
Installing collected packages: pyvirtualdisplay
  Running setup.py install for pyvirtualdisplay ... error
Exception:
Traceback (most recent call last):
  File "c:\users\pedro maurício\appdata\local\programs\python\python36-32\lib\si
te-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 76: invalid
 continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\pedro maurício\appdata\local\programs\python\python36-32\lib\si
te-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\pedro maurício\appdata\local\programs\python\python36-32\lib\si
te-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\users\pedro maurício\appdata\local\programs\python\python36-32\lib\si
te-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\users\pedro maurício\appdata\local\programs\python\python36-32\lib\si
te-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\users\pedro maurício\appdata\local\programs\python\python36-32\lib\si
te-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\users\pedro maurício\appdata\local\programs\python\python36-32\lib\si
te-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 76: invalid
 continuation byte
__

The last part appears in the cmd in the red color. 
What happened?

**Comment by guggze** [comment]
I am getting the same too

**Comment by Nemixalone** [comment]
Please read this [article](https://stackoverflow.com/questions/35510743/error-while-upgrading-pip-unicodedecodeerror-utf-8-codec-cant-decode-byte). It's because your name is **c:\users\pedro maurício** the **í** is not in utf-8 coding. Try this fix or search somewhere else.
