### ISSUE TITLE
care about using this!!!! 

### ISSUE THREAD

**Issue by 1saeedsalehi** [Nemixalone/GUI-tool-for-InstaPy-script#26]
this tool hacks your instagram account

**Comment by Nemixalone** [comment]
Are you for real ?

**Comment by 1saeedsalehi** [comment]
@Nemixalone  yes, when I was using this tool, after 5 mins suddenly I logged out and my recovery email and all of my account information was changed,

**Comment by justinf102** [comment]
wtf

**Comment by Nemixalone** [comment]
Its not InstaPy nor GUI error that lead you got hacked, but the fact that your password was weak af. So dont blame us.

**Comment by justinf102** [comment]
Lmao

**Comment by 1saeedsalehi** [comment]
it's just a caution about using this, I use a complex password and just logged in with official Instagram app and instapy using GUI
