### ISSUE TITLE
Can't run it on Mac-Instapy folder & chromedriver missing

### ISSUE THREAD

**Issue by Lukavalls** [Nemixalone/GUI-tool-for-InstaPy-script#28]
Hi there,

I just try to run Instapy and I have this two problems. Any suggestions? Thanks!

<img width="1095" alt="captura de pantalla 2017-12-07 a las 0 31 43" src="https://user-images.githubusercontent.com/34323032/33690953-2c6cad8c-dae6-11e7-9863-18c9cd0d736e.png">

**Comment by CiprianDe** [comment]
Hey there! 

for "instapy folder is missing" you need to set the right path. that one with instypy-master , not the electron-instapy-GUI. 

and  for the chromedriver, i don:t know yet. I have the same problem. 

Please let me know if you get iti done.

**Comment by Nemixalone** [comment]
This is not my app. So i cant give any info. Please post it on official page. Thanks
