### ISSUE TITLE
chromedriver is missing! 

### ISSUE THREAD

**Issue by CiprianDe** [Nemixalone/GUI-tool-for-InstaPy-script#29]
Hello there! 

I just tried to run InstaPy but it's telling me that chromedriver is missing. 
![ice_screenshot_20171211-230247](https://user-images.githubusercontent.com/34459675/33868689-b2ca88fa-df04-11e7-8dc4-66527e584b36.png)

Any ideas?

**Comment by Ishaan0905** [comment]
Same Issue

**Comment by Nemixalone** [comment]
Hi this is not my app and i cant tell any info. Please post it on official page. Thanks

**Comment by OGHARRY** [comment]
Put chromedriver inside your assets folder that should fix it, if not try checking its path https://www.youtube.com/watch?v=dz59GsdvUF8 let me know if you are stilling having trouble

**Comment by CiprianDe** [comment]
Hi!

Chromedriver is already in assets folder, and  I followed also the path of chromedriver installation and the cmd says that is installed. When I try to run InstapyGUI, even if doesn't recognize the driver it's giving me this like error 
![ice_screenshot_20171221-180916](https://user-images.githubusercontent.com/34459675/34266869-096942a0-e67b-11e7-880d-114002fd0ec6.png)

I appreciate your help!
