### ISSUE TITLE
Looks Good

### ISSUE THREAD

**Issue by littleswany** [Nemixalone/GUI-tool-for-InstaPy-script#3]
Hey,

I saw that you were working on this from the main Repo of Insta Py. Unfortunately I can't test it as I am on OSX but from what I can see it looks like it is going well!

**Comment by Nemixalone** [comment]
Thanks but as mentioned by Tim it's for Windows only that's little naah we can try web GUI as you proposed or I can try switching to QT. However we agree on proceeding with GUI I am on board to contribute. :)

**Comment by littleswany** [comment]
I will put something together either in JS or PHP this week and I'll get
back to you. Windows is good for Windows people tho!

What's QT? Don't think I have come across it before?

**Comment by Nemixalone** [comment]
[QT](https://en.wikipedia.org/wiki/Qt_(software)) is a cross-platform application framework that is used for developing application software that can be run on various software and hardware platforms with little or no change in the underlying codebase. 

Will you create repo for that or you can contact me here.
