### ISSUE TITLE
GUI doesn't seem to be working for me.

### ISSUE THREAD

**Issue by johnnydavis60** [Nemixalone/GUI-tool-for-InstaPy-script#4]
I have downloaded the requirements I believe and when I do for instance likes from tag, login and click run it brings a cmd prompt for half a second and closes. Instagram is not showing and liked pictures.

**Comment by Nemixalone** [comment]
Go to InstaPy folder press **SHIFT + RIGHT CLICK** and **open command window here** and type **Start.bat** and paste error here.

**Comment by johnnydavis60** [comment]
C:\Users\ndaou\Downloads\GUI-tool-for-InstaPy-script-master\GUI-tool-for-InstaPy-script-master\InstaPy\obj\Debug\InstaPy-master>py quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "C:\Users\ndaou\Downloads\GUI-tool-for-InstaPy-script-master\GUI-tool-for-InstaPy-script-master\InstaPy\obj\Debug\InstaPy-master\instapy\__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "C:\Users\ndaou\Downloads\GUI-tool-for-InstaPy-script-master\GUI-tool-for-InstaPy-script-master\InstaPy\obj\Debug\InstaPy-master\instapy\instapy.py", line 5, in <module>
    from pyvirtualdisplay import Display
  File "C:\Users\ndaou\Downloads\GUI-tool-for-InstaPy-script-master\GUI-tool-for-InstaPy-script-master\InstaPy\obj\Debug\InstaPy-master\pyvirtualdisplay\__init__.py", line 3, in <module>
    from pyvirtualdisplay.display import Display
  File "C:\Users\ndaou\Downloads\GUI-tool-for-InstaPy-script-master\GUI-tool-for-InstaPy-script-master\InstaPy\obj\Debug\InstaPy-master\pyvirtualdisplay\display.py", line 1, in <module>
    from pyvirtualdisplay.abstractdisplay import AbstractDisplay
  File "C:\Users\ndaou\Downloads\GUI-tool-for-InstaPy-script-master\GUI-tool-for-InstaPy-script-master\InstaPy\obj\Debug\InstaPy-master\pyvirtualdisplay\abstractdisplay.py", line 1, in <module>
    from easyprocess import EasyProcess
ModuleNotFoundError: No module named 'easyprocess'

**Comment by Nemixalone** [comment]
Use pip to install **easyprocess** module.

**pip install EasyProcess**

**Comment by Nemixalone** [comment]
Fixed ?

**Comment by johnnydavis60** [comment]
I installed EasyProcess and it then told me to install clarifai, so I tried to pip install clarifai and it gave me an error 


Collecting clarifai
  Using cached clarifai-2.0.21.tar.gz
Requirement already satisfied: future==0.15.2 in c:\users\ndaou\appdata\local\programs\python\python36\lib\site-packages (from clarifai)
Requirement already satisfied: requests==2.13.0 in c:\users\ndaou\appdata\local\programs\python\python36\lib\site-packages (from clarifai)
Requirement already satisfied: configparser==3.5.0 in c:\users\ndaou\appdata\local\programs\python\python36\lib\site-packages (from clarifai)
Requirement already satisfied: jsonschema==2.5.1 in c:\users\ndaou\appdata\local\programs\python\python36\lib\site-packages (from clarifai)
Collecting Pillow==2.9.0 (from clarifai)
  Using cached Pillow-2.9.0.zip
Installing collected packages: Pillow, clarifai
  Running setup.py install for Pillow ... error
    Complete output from command c:\users\ndaou\appdata\local\programs\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ndaou\\AppData\\Local\\Temp\\pip-build-4stlo486\\Pillow\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ndaou\AppData\Local\Temp\pip-8m55nlkm-record\install-record.txt --single-version-externally-managed --compile:
    Single threaded build, not installing mp_compile: 4 processes
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\PIL
    copying PIL\BdfFontFile.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\BmpImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\BufrStubImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ContainerIO.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\CurImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\DcxImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\EpsImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ExifTags.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\features.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\FitsStubImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\FliImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\FontFile.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\FpxImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\GbrImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\GdImageFile.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\GifImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\GimpGradientFile.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\GimpPaletteFile.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\GribStubImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\Hdf5StubImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\IcnsImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\IcoImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\Image.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageChops.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageCms.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageColor.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageDraw.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageDraw2.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageEnhance.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageFile.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageFileIO.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageFilter.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageFont.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageGrab.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageMath.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageMode.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageMorph.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageOps.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImagePalette.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImagePath.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageQt.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageSequence.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageShow.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageStat.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageTk.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageTransform.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageWin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImtImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\IptcImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\Jpeg2KImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\JpegImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\JpegPresets.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\McIdasImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\MicImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\MpegImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\MpoImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\MspImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\OleFileIO.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PaletteFile.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PalmImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PcdImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PcfFontFile.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PcxImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PdfImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PixarImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PngImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PpmImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PsdImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PSDraw.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PyAccess.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\SgiImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\SpiderImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\SunImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\TarIO.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\TgaImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\TiffImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\TiffTags.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\WalImageFile.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\WebPImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\WmfImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\XbmImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\XpmImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\XVThumbImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\_binary.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\_util.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\__init__.py -> build\lib.win-amd64-3.6\PIL
    running egg_info
    writing Pillow.egg-info\PKG-INFO
    writing dependency_links to Pillow.egg-info\dependency_links.txt
    writing top-level names to Pillow.egg-info\top_level.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'Pillow.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'Pillow.egg-info\SOURCES.txt'
    copying PIL\OleFileIO-README.md -> build\lib.win-amd64-3.6\PIL
    running build_ext
    building 'PIL._imaging' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\libImaging
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\ndaou\AppData\Local\Temp\pip-build-4stlo486\Pillow\libImaging -Ic:\users\ndaou\appdata\local\programs\python\python36\include -Ic:\users\ndaou\appdata\local\programs\python\python36\include -Ic:\users\ndaou\appdata\local\programs\python\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" /Tc_imaging.c /Fobuild\temp.win-amd64-3.6\Release\_imaging.obj
    _imaging.c
    c:\users\ndaou\appdata\local\programs\python\python36\include\pyconfig.h(222): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

**Comment by Nemixalone** [comment]
Go to folder **instapy** inside **master** folder open **instapy.py** file in some editor and remove line **import here-is-something from clarifai**

**Comment by johnnydavis60** [comment]
I don't seem to have "import here-is-something from clarifai"

**Comment by Nemixalone** [comment]
Is there anything that says import from clarifai in first few lines

**Comment by johnnydavis60** [comment]
Yes I see this "from .clarifai_util import check_image"
I tried to delete that and I got the same error

**Comment by johnnydavis60** [comment]
never mind, removing that line fixes the Start.bat and should be working all fine now

**Comment by Nemixalone** [comment]
**From clarifai.client import clarifiapi** that line

**Comment by Nemixalone** [comment]
No problem :)
