### ISSUE TITLE
No module named 'clarifai' ?

### ISSUE THREAD

**Issue by shiv248** [Nemixalone/GUI-tool-for-InstaPy-script#5]
Hey folks, I'm just a bit confused as to why this error is happening, and if you could help me fix it.
![image](https://cloud.githubusercontent.com/assets/15200155/25553359/fecc875a-2c65-11e7-9990-2f8af7cee0de.png)

**Comment by Nemixalone** [comment]
Hello,
There is two solutions to try.

You can install **clarifai** module using pip - **pip install clarifai**
OR
Go to **instapy** folder find **clarifai_util.py** open it in some text editor and delete that line you highlighted.

**Comment by shiv248** [comment]
When I pip install clarifai this error comes up :(
![image](https://cloud.githubusercontent.com/assets/15200155/25553482/dc524716-2c68-11e7-9fb6-0d93cee8d8de.png)

**Comment by Nemixalone** [comment]
Huh :hammer: 

Try solution number 2.

**Comment by Nemixalone** [comment]
Fixed ?
