### ISSUE TITLE
Error Not all files are downloaded! 

### ISSUE THREAD

**Issue by gitjayjay** [Nemixalone/GUI-tool-for-InstaPy-script#7]
I've dl'd everything and dragged the GUI into the instapy folder.... still says not all files are downloaded when I try to run the GUI .... Thanks for the help!

**Comment by Nemixalone** [comment]
Can you screenshot main folder of InstaPy and send me can you try to restart app.

**Comment by gitjayjay** [comment]
![instapy](https://cloud.githubusercontent.com/assets/26553150/26027904/b94b0714-37d3-11e7-9d30-7f02b5facdcf.JPG)

**Comment by Nemixalone** [comment]
Please delete everything except InstaPy-GUI.exe, those files are project files for programming you need to download [this zip](https://github.com/timgrossmann/InstaPy/archive/master.zip) extract it somewhere and put InstaPy-GUI.exe in that folder. Please read all requirements for InstaPy from their [official page](https://github.com/timgrossmann/InstaPy#you-need-to-have-python-27-or-36-installed-setted-up-path-for-py-command-installed-selenium-and-pyvirtualdriver). Hope it helps. :serbia:  :smiley_cat:

**Comment by gitjayjay** [comment]
hey Nenmanja, thank you thank you for all the help so far.... the GUI reads all Instapy files are there and when I run it, the screen prompted my terminal for 1 sec and it disappeared... how do I know if it worked/went through?

**Comment by Nemixalone** [comment]
It's free no hosting needed, hold **SHIFT** and press **right click** now select **open command window here** and type **py quickstart.py** and copy error message.

**Comment by gitjayjay** [comment]
(ModuleNotFoundError: No module named 'pyvirtualdisplay' )  I put the download pyvirtualdisplay file into assets but it seems to not work still

**Comment by Nemixalone** [comment]
You need to install module using pip
**pip install pyvirtualdisplay** also you need **pip install selenium** and you need **chromedriver.exe** to put into **assets**

**Comment by gitjayjay** [comment]
I do have all those installed : 

C:\Users\crazycanuck101\Desktop\InstaPy-master>pip install pyvirtualdisplay
Requirement already satisfied (use --upgrade to upgrade): pyvirtualdisplay in c:\users\crazycanuck101\anaconda3\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): EasyProcess in c:\users\crazycanuck101\anaconda3\lib\site-packages (from pyvirtualdisplay)
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\crazycanuck101\Desktop\InstaPy-master>pip install selenium
Requirement already satisfied (use --upgrade to upgrade): selenium in c:\users\crazycanuck101\anaconda3\lib\site-packages
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\crazycanuck101\Desktop\InstaPy-master>

what's the issue now ? and yes chromedriver is in assets

**Comment by Nemixalone** [comment]
Try **pip install EasyProcess** if that doesn't work. I would ask you to put Issue on official page of [InstaPy](https://github.com/timgrossmann/InstaPy)
