### ISSUE TITLE
Chromedriver.exe

### ISSUE THREAD

**Issue by Iamstuck** [Nemixalone/GUI-tool-for-InstaPy-script#9]
Okay I don't know anything about complicated computer stuff I just need a bot for my Instagram. 

I have moved the chrome driver download into the assets folder but it still says that I need to download the chromedriver.exe at the moment it is the chromedriver application so I don't know if I have downloaded the right bit?

Thanks 
#helpme

**Comment by Nemixalone** [comment]
So you have downloaded all [InstaPy](https://github.com/timgrossmann/InstaPy) files. Also Downloaded chromedriver.exe from [here](https://chromedriver.storage.googleapis.com/index.html?path=2.29/) putted in Assets. Right? Now put InstaPy-GUI.exe inside InstaPy main folder like on the picture below. Also have you installed [Python](https://www.python.org/downloads/) and [Selenium](http://selenium-python.readthedocs.io/) and [pyvirtualdisplay](https://pypi.python.org/pypi/PyVirtualDisplay) ?
If you have done everything you can start up InstaPy-GUI.exe and try to run it. You will need username,password and at least one hashtag for liking(so bot can actually like something). I would recommend that you read [InstaPy readme] (https://github.com/timgrossmann/InstaPy#restricting-likes) from here to down so you could insert all necessary things into InstaPy-GUI. If you have any problems or questions feel free to ask :question:. :smile: 
![untitled](https://cloud.githubusercontent.com/assets/7568344/26222292/bb626200-3c19-11e7-9eb4-7b68ae0c6b14.png)

**Comment by nate2799** [comment]
I have downloaded all of the requirements and the program says "All instpy files are there".  I fill in my login and select a tag.  I click run and it seems to attempt to start but then instantly closes the command box back down.  I took a print screen of the moment I clicked run.  Any ideas as to where I am going wrong?

I have chrome driver in assets
instapy.exe in main folder as you have pictured
I have installed Python and Selenium and pyvirtualdisplay 

![instapy issues](https://cloud.githubusercontent.com/assets/29220989/26814435/935120c4-4a53-11e7-8563-39a727e8c5e8.png)

**Comment by marudon** [comment]
Open a command Box and then type "Start.bat". Then you can See the error message.

Von meinem iPhone gesendet

**Comment by nate2799** [comment]
It says, windows cannot find ".bat"

Nathan Dunlop



Address: 212-1335 carling ave, ottawa K1Z 8N8

Alt Address: 26-1010 polytek st, ottawa, on, K1J 9J1

Phone: 613-698-3564

Fax: 613-688-9920
ndunlop@mortgagealliance.com
info@modernpropertyottawa.com
<https://ca.linkedin.com/in/nathan-dunlop>

**Comment by marudon** [comment]
Open you command box at the path where you start.bat is

**Comment by Nemixalone** [comment]
Go to InstaPy folder where are all file press **SHIFT + RIGHT CLICK** and choose **OPEN COMMADN WINDOW HERE** type **start.bat** and copy/screenshot the error and post it.

**Comment by nate2799** [comment]
Okay I will do this tonight.  Thank you very much for these responses.

**Comment by nate2799** [comment]
I've tried start.bat.  Just tells me it can't find .bat

I've tried it at varying folders but same error response.

Here is the error code I received while running windows.ps1


​

Nathan Dunlop



Address: 212-1335 carling ave, ottawa K1Z 8N8

Alt Address: 26-1010 polytek st, ottawa, on, K1J 9J1

Phone: 613-698-3564

Fax: 613-688-9920
ndunlop@mortgagealliance.com
info@modernpropertyottawa.com
<https://ca.linkedin.com/in/nathan-dunlop>

**Comment by nate2799** [comment]
Here is the location of selenium and pyvirtual display


​

Nathan Dunlop



Address: 212-1335 carling ave, ottawa K1Z 8N8

Alt Address: 26-1010 polytek st, ottawa, on, K1J 9J1

Phone: 613-698-3564

Fax: 613-688-9920
ndunlop@mortgagealliance.com
info@modernpropertyottawa.com
<https://ca.linkedin.com/in/nathan-dunlop>

**Comment by nate2799** [comment]
Here is a little more visual info for you.


​

Nathan Dunlop



Address: 212-1335 carling ave, ottawa K1Z 8N8

Alt Address: 26-1010 polytek st, ottawa, on, K1J 9J1

Phone: 613-698-3564

Fax: 613-688-9920
ndunlop@mortgagealliance.com
info@modernpropertyottawa.com
<https://ca.linkedin.com/in/nathan-dunlop>

**Comment by nate2799** [comment]
more visuals


​

Nathan Dunlop



Address: 212-1335 carling ave, ottawa K1Z 8N8

Alt Address: 26-1010 polytek st, ottawa, on, K1J 9J1

Phone: 613-698-3564

Fax: 613-688-9920
ndunlop@mortgagealliance.com
info@modernpropertyottawa.com
<https://ca.linkedin.com/in/nathan-dunlop>

**Comment by Nemixalone** [comment]
I can't see pictures if you posted that.

**Comment by nate2799** [comment]
Okay.  They were added to this email thread.  Did you want me posting in
GitHub instead?

Nathan Dunlop



Address: 212-1335 carling ave, ottawa K1Z 8N8

Alt Address: 26-1010 polytek st, ottawa, on, K1J 9J1

Phone: 613-698-3564

Fax: 613-688-9920
ndunlop@mortgagealliance.com
info@modernpropertyottawa.com
<https://ca.linkedin.com/in/nathan-dunlop>

On Sat, Jun 10, 2017 at 11:44 AM, Nemanja Komadina <notifications@github.com

**Comment by Nemixalone** [comment]
Yes you are posting nowthign on Github from mail and we can't see anything here and neither in mail.

**Comment by nate2799** [comment]
Okay perfect.

I just edited all of my previous comments and uploaded the screen shots to
each

Nathan Dunlop



Address: 212-1335 carling ave, ottawa K1Z 8N8

Alt Address: 26-1010 polytek st, ottawa, on, K1J 9J1

Phone: 613-698-3564

Fax: 613-688-9920
ndunlop@mortgagealliance.com
info@modernpropertyottawa.com
<https://ca.linkedin.com/in/nathan-dunlop>

On Sat, Jun 10, 2017 at 11:51 AM, Nemanja Komadina <notifications@github.com

**Comment by Nemixalone** [comment]
You see in **master** folder (first picture) you have start.bat. Now press **SHIFT** and **RIGHT CLICK** and you will see **Open command window here** and select it. Now when Command window shows up type **St** and press tab to auto complete **Start.bat**. After that you can see all errors that occured.

**Comment by nate2799** [comment]
Okay here it is.

![startbat](https://user-images.githubusercontent.com/29220989/27004449-4810acf6-4dd7-11e7-9b14-d3c7694d5ba2.png)

**Comment by Nemixalone** [comment]
Read [this](https://stackoverflow.com/questions/32742093/how-to-access-python-from-command-line-using-py-instead-of-python) and try to fix it.

**Comment by nate2799** [comment]
Seems to be getting closer.  Here is the newest response 
![pyton install repair](https://user-images.githubusercontent.com/29220989/27004727-4f75a4a6-4ddc-11e7-81e8-62a8a34cd080.png)

**Comment by Nemixalone** [comment]
install **Pyvirtualdisplay**

**Comment by nate2799** [comment]
was having issues installing pyvirtualdisplay and selenium.  fixed and installed now.  Here is the newest issue when I run GUI
![new error running gui](https://user-images.githubusercontent.com/29220989/27005091-16d7c38c-4de5-11e7-98e2-b376ec058db2.png)

**Comment by Nemixalone** [comment]
Go to **instapy** folder (NOT MASTER BUT THE ONE WITH ALL .PY FILES) picture number 2 you send today. Open **instapy.py** file with notepad search for this line(it's like 10th line in file) and delete it **from .clarifai_util import check_image**, save it and run it.

**Comment by nate2799** [comment]
ok perfect.  Did that and then got a reference to "emoji"
![emoji](https://user-images.githubusercontent.com/29220989/27005427-854e1a8a-4dec-11e7-93dc-b21f4a4f63f9.png)

**Comment by Nemixalone** [comment]
pip install emoji

**Comment by nate2799** [comment]
It's working.  I have it set up for my login and likes at the moment.  I'll
tinker to see if there are any more issues.

Thank you very much for all of your help and patience.  This is an amazing
program!

Nathan Dunlop



Address: 212-1335 carling ave, ottawa K1Z 8N8

Alt Address: 26-1010 polytek st, ottawa, on, K1J 9J1

Phone: 613-698-3564

Fax: 613-688-9920
ndunlop@mortgagealliance.com
info@modernpropertyottawa.com
<https://ca.linkedin.com/in/nathan-dunlop>

**Comment by Nemixalone** [comment]
No problem I am glad I helped. If you have any questions please feel free to ask, you can do that by opening new Issue or emailing me. :smile: :man_farmer:
